deluge:
  client: deluge
  host: 127.0.0.1:58846
  username: dddd
  password: dddd1111
  strategies:
    all:
      seeding_time: 22100
      free_space:
        min: 100
        path: /home/dddd/deluge/download/
        action: remove-inactive-seeds

    delete_by_error:
      status:
        - Error
      create_time: 3600

  delete_data: true

qbittorrent:
  client: qbittorrent
  host: http://127.0.0.1:2017
  username: dddd
  password: dddd1111
  strategies:
    all:
      seeding_time: 22100
      free_space:
        min: 150
        path: /home/dddd/deluge/download/
        action: remove-inactive-seeds

    delete_by_error:
      status: Error
      create_time: 3600
 

  delete_data: true
