deluge:
  client: deluge
  host: 127.0.0.1:58846
  username: pppppp
  password: BB123123
  strategies:
    all:
      seeding_time: 22100
      free_space:
        min: 100
        path: /home/pppppp/deluge/download/
        action: remove-inactive-seeds

    delete_by_error:
      status:
        - Error
      create_time: 3600

  delete_data: true

qbittorrent:
  client: qbittorrent
  host: http://127.0.0.1:2017
  username: pppppp
  password: BB123123
  strategies:
    all:
      seeding_time: 22100
      free_space:
        min: 150
        path: /home/pppppp/deluge/download/
        action: remove-inactive-seeds

    delete_by_error:
      status: Error
      create_time: 3600
 

  delete_data: true
